on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:latest
    name: Build

    strategy:
      matrix:
        include:
          - board: seeeduino_xiao_ble
            shield: charybdis_dongle prospector_adapter

          - board: nice_nano_v2
            shield: charybdis_left

          - board: nice_nano_v2
            shield: charybdis_right

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: zmkfirmware/zmk-build-action@v1
        with:
          board: ${{ matrix.board }}
          shield: ${{ matrix.shield }}
          extra-cmake-args: ${{ matrix.cmake-args }}
          artifact-name: ${{ matrix.board }}-${{ matrix.shield }}
          config-path: config

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: firmware
          path: firmware/zmk.uf2
          if-no-files-found: ignore